#!/bin/sh
#
# gridftp-lfs A gridftp server for LFS
#
# chkconfig:   345 99 1
# description: Starts the Globus GridFTP server with the \
#              LFS DSI module.

# Source function library.
. /etc/rc.d/init.d/functions

exec="NONE/sbin/globus-gridftp-server"
prog="gridftp-lfs"
config="/home/meloam/ANSE/local/etc/gridftp-lfs/gridftp.conf"

. ${prefix}/share/$prog/$prog-environment

[ -e /home/meloam/ANSE/local/etc/sysconfig/gridftp.conf.d/$prog ] && . /home/meloam/ANSE/local/etc/sysconfig/gridftp.conf.d/$prog

lockfile=/home/meloam/ANSE/local/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon $exec -c $config -pidfile /home/meloam/ANSE/local/var/run/$prog.pid
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?

